#!/usr/bin/env php
<?php

declare(strict_types=1);
defined('PHALCON_DEBUG') or define('PHALCON_DEBUG', false);
defined('PHALCON_ENV') or define('PHALCON_ENV', 'prod');
defined('ROOT_PATH') or define('ROOT_PATH', __DIR__);
defined('APP_PATH') or define('APP_PATH', ROOT_PATH . '/console');

use Phalcon\Cli\Console;
use Phalcon\Config;
use Phalcon\Di\FactoryDefault\Cli;
use Phalcon\Exception as PhalconException;

require ROOT_PATH . '/vendor/autoload.php';

/**
 * Read the configuration
 */
$config = new Config(array_merge(
    require ROOT_PATH . "/console/config/config.php",
    require ROOT_PATH . "/console/config/config-local.php",
));

/**
 * Read auto-loader
 */
require ROOT_PATH . '/common/config/loader.php';
require ROOT_PATH . '/console/config/loader.php';

/**
 * Read services
 */
require ROOT_PATH . "/console/config/services.php";

/**
 * @var Cli $container
 */
$console = new Console($container);

$arguments = [];
foreach ($argv as $k => $arg) {
    if ($k === 1) {
        $arguments['task'] = $arg;
    } elseif ($k === 2) {
        $arguments['action'] = $arg;
    } elseif ($k >= 3) {
        $arguments['params'][] = $arg;
    }
}

try {
    $console->handle($arguments);
} catch (PhalconException|Throwable|Exception $e) {
    fwrite(STDERR, $e->getMessage() . PHP_EOL);
    exit(1);
}
